# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and publish test coverage

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checks out rep
      uses: actions/checkout@v2.3.4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM dependencies
      run: npm install
    - name: Run Jest tests and generate coverage report
      run: npm run test:coverage
    - name: Publish test coverage report
      uses: EndBug/add-and-commit@v7.4.0
      with:
        add: docs
        force: true
        message: Add generated coverage doc
      env:
        GITHUB_TOKEN: $
